
version: '3.8'


services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=oauth-service
      - MYSQL_ROOT_PASSWORD=1234567890
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - docker-net


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - docker-net


  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - docker-net

  oauth-service:
    depends_on:
      - mysqldb
    image: durutheguru/oauth-service:latest
    restart: always
    ports:
      - "10101:10101"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/oauth-service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234567890
    stdin_open: true
    tty: true
    networks:
      - docker-net


volumes:
  db:


networks:
  docker-net:


