/*
 * This file is generated by jOOQ.
 */
package com.julianduru.oauthservice.jooq.tables;


import com.julianduru.oauthservice.jooq.Keys;
import com.julianduru.oauthservice.jooq.OauthService;
import com.julianduru.oauthservice.jooq.tables.records.ResourceServerAllowedScopesRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourceServerAllowedScopes extends TableImpl<ResourceServerAllowedScopesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>oauth_service.resource_server_allowed_scopes</code>
     */
    public static final ResourceServerAllowedScopes RESOURCE_SERVER_ALLOWED_SCOPES = new ResourceServerAllowedScopes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResourceServerAllowedScopesRecord> getRecordType() {
        return ResourceServerAllowedScopesRecord.class;
    }

    /**
     * The column <code>oauth_service.resource_server_allowed_scopes.resource_server_id</code>.
     */
    public final TableField<ResourceServerAllowedScopesRecord, Long> RESOURCE_SERVER_ID = createField(DSL.name("resource_server_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>oauth_service.resource_server_allowed_scopes.allowed_scopes</code>.
     */
    public final TableField<ResourceServerAllowedScopesRecord, String> ALLOWED_SCOPES = createField(DSL.name("allowed_scopes"), SQLDataType.VARCHAR(255), this, "");

    private ResourceServerAllowedScopes(Name alias, Table<ResourceServerAllowedScopesRecord> aliased) {
        this(alias, aliased, null);
    }

    private ResourceServerAllowedScopes(Name alias, Table<ResourceServerAllowedScopesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>oauth_service.resource_server_allowed_scopes</code> table reference
     */
    public ResourceServerAllowedScopes(String alias) {
        this(DSL.name(alias), RESOURCE_SERVER_ALLOWED_SCOPES);
    }

    /**
     * Create an aliased <code>oauth_service.resource_server_allowed_scopes</code> table reference
     */
    public ResourceServerAllowedScopes(Name alias) {
        this(alias, RESOURCE_SERVER_ALLOWED_SCOPES);
    }

    /**
     * Create a <code>oauth_service.resource_server_allowed_scopes</code> table reference
     */
    public ResourceServerAllowedScopes() {
        this(DSL.name("resource_server_allowed_scopes"), null);
    }

    public <O extends Record> ResourceServerAllowedScopes(Table<O> child, ForeignKey<O, ResourceServerAllowedScopesRecord> key) {
        super(child, key, RESOURCE_SERVER_ALLOWED_SCOPES);
    }

    @Override
    public Schema getSchema() {
        return OauthService.OAUTH_SERVICE;
    }

    @Override
    public List<ForeignKey<ResourceServerAllowedScopesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ResourceServerAllowedScopesRecord, ?>>asList(Keys.FKHF7RY24VOX7A9PO1E108JD3DG);
    }

    private transient ResourceServer _resourceServer;

    public ResourceServer resourceServer() {
        if (_resourceServer == null)
            _resourceServer = new ResourceServer(this, Keys.FKHF7RY24VOX7A9PO1E108JD3DG);

        return _resourceServer;
    }

    @Override
    public ResourceServerAllowedScopes as(String alias) {
        return new ResourceServerAllowedScopes(DSL.name(alias), this);
    }

    @Override
    public ResourceServerAllowedScopes as(Name alias) {
        return new ResourceServerAllowedScopes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResourceServerAllowedScopes rename(String name) {
        return new ResourceServerAllowedScopes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResourceServerAllowedScopes rename(Name name) {
        return new ResourceServerAllowedScopes(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
