/*
 * This file is generated by jOOQ.
 */
package com.julianduru.oauthservice.jooq.tables;


import com.julianduru.oauthservice.jooq.Keys;
import com.julianduru.oauthservice.jooq.OauthService;
import com.julianduru.oauthservice.jooq.tables.records.ResourceServerUserAuthoritiesOnSignUpRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourceServerUserAuthoritiesOnSignUp extends TableImpl<ResourceServerUserAuthoritiesOnSignUpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>oauth_service.resource_server_user_authorities_on_sign_up</code>
     */
    public static final ResourceServerUserAuthoritiesOnSignUp RESOURCE_SERVER_USER_AUTHORITIES_ON_SIGN_UP = new ResourceServerUserAuthoritiesOnSignUp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResourceServerUserAuthoritiesOnSignUpRecord> getRecordType() {
        return ResourceServerUserAuthoritiesOnSignUpRecord.class;
    }

    /**
     * The column <code>oauth_service.resource_server_user_authorities_on_sign_up.resource_server_id</code>.
     */
    public final TableField<ResourceServerUserAuthoritiesOnSignUpRecord, Long> RESOURCE_SERVER_ID = createField(DSL.name("resource_server_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>oauth_service.resource_server_user_authorities_on_sign_up.user_authorities_on_sign_up</code>.
     */
    public final TableField<ResourceServerUserAuthoritiesOnSignUpRecord, String> USER_AUTHORITIES_ON_SIGN_UP = createField(DSL.name("user_authorities_on_sign_up"), SQLDataType.VARCHAR(255), this, "");

    private ResourceServerUserAuthoritiesOnSignUp(Name alias, Table<ResourceServerUserAuthoritiesOnSignUpRecord> aliased) {
        this(alias, aliased, null);
    }

    private ResourceServerUserAuthoritiesOnSignUp(Name alias, Table<ResourceServerUserAuthoritiesOnSignUpRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>oauth_service.resource_server_user_authorities_on_sign_up</code> table reference
     */
    public ResourceServerUserAuthoritiesOnSignUp(String alias) {
        this(DSL.name(alias), RESOURCE_SERVER_USER_AUTHORITIES_ON_SIGN_UP);
    }

    /**
     * Create an aliased <code>oauth_service.resource_server_user_authorities_on_sign_up</code> table reference
     */
    public ResourceServerUserAuthoritiesOnSignUp(Name alias) {
        this(alias, RESOURCE_SERVER_USER_AUTHORITIES_ON_SIGN_UP);
    }

    /**
     * Create a <code>oauth_service.resource_server_user_authorities_on_sign_up</code> table reference
     */
    public ResourceServerUserAuthoritiesOnSignUp() {
        this(DSL.name("resource_server_user_authorities_on_sign_up"), null);
    }

    public <O extends Record> ResourceServerUserAuthoritiesOnSignUp(Table<O> child, ForeignKey<O, ResourceServerUserAuthoritiesOnSignUpRecord> key) {
        super(child, key, RESOURCE_SERVER_USER_AUTHORITIES_ON_SIGN_UP);
    }

    @Override
    public Schema getSchema() {
        return OauthService.OAUTH_SERVICE;
    }

    @Override
    public List<ForeignKey<ResourceServerUserAuthoritiesOnSignUpRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ResourceServerUserAuthoritiesOnSignUpRecord, ?>>asList(Keys.FKGCI54Q6HD92GHWDN0OS64FV9O);
    }

    private transient ResourceServer _resourceServer;

    public ResourceServer resourceServer() {
        if (_resourceServer == null)
            _resourceServer = new ResourceServer(this, Keys.FKGCI54Q6HD92GHWDN0OS64FV9O);

        return _resourceServer;
    }

    @Override
    public ResourceServerUserAuthoritiesOnSignUp as(String alias) {
        return new ResourceServerUserAuthoritiesOnSignUp(DSL.name(alias), this);
    }

    @Override
    public ResourceServerUserAuthoritiesOnSignUp as(Name alias) {
        return new ResourceServerUserAuthoritiesOnSignUp(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ResourceServerUserAuthoritiesOnSignUp rename(String name) {
        return new ResourceServerUserAuthoritiesOnSignUp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ResourceServerUserAuthoritiesOnSignUp rename(Name name) {
        return new ResourceServerUserAuthoritiesOnSignUp(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
