/*
 * This file is generated by jOOQ.
 */
package com.julianduru.oauthservice.jooq.tables.records;


import com.julianduru.oauthservice.jooq.tables.QueueIncomingMessage;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QueueIncomingMessageRecord extends UpdatableRecordImpl<QueueIncomingMessageRecord> implements Record11<Long, String, String, Integer, String, String, String, String, Boolean, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oauth_service.queue_incoming_message.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oauth_service.queue_incoming_message.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oauth_service.queue_incoming_message.header</code>.
     */
    public void setHeader(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oauth_service.queue_incoming_message.header</code>.
     */
    public String getHeader() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oauth_service.queue_incoming_message.payload</code>.
     */
    public void setPayload(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oauth_service.queue_incoming_message.payload</code>.
     */
    public String getPayload() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oauth_service.queue_incoming_message.processing_status</code>.
     */
    public void setProcessingStatus(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>oauth_service.queue_incoming_message.processing_status</code>.
     */
    public Integer getProcessingStatus() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>oauth_service.queue_incoming_message.processing_status_message</code>.
     */
    public void setProcessingStatusMessage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oauth_service.queue_incoming_message.processing_status_message</code>.
     */
    public String getProcessingStatusMessage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oauth_service.queue_incoming_message.reference</code>.
     */
    public void setReference(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oauth_service.queue_incoming_message.reference</code>.
     */
    public String getReference() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oauth_service.queue_incoming_message.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oauth_service.queue_incoming_message.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>oauth_service.queue_incoming_message.topic</code>.
     */
    public void setTopic(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>oauth_service.queue_incoming_message.topic</code>.
     */
    public String getTopic() {
        return (String) get(7);
    }

    /**
     * Setter for <code>oauth_service.queue_incoming_message.treat_immediately</code>.
     */
    public void setTreatImmediately(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>oauth_service.queue_incoming_message.treat_immediately</code>.
     */
    public Boolean getTreatImmediately() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>oauth_service.queue_incoming_message.time_added</code>.
     */
    public void setTimeAdded(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>oauth_service.queue_incoming_message.time_added</code>.
     */
    public String getTimeAdded() {
        return (String) get(9);
    }

    /**
     * Setter for <code>oauth_service.queue_incoming_message.time_updated</code>.
     */
    public void setTimeUpdated(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>oauth_service.queue_incoming_message.time_updated</code>.
     */
    public String getTimeUpdated() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, Integer, String, String, String, String, Boolean, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, String, Integer, String, String, String, String, Boolean, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return QueueIncomingMessage.QUEUE_INCOMING_MESSAGE.ID;
    }

    @Override
    public Field<String> field2() {
        return QueueIncomingMessage.QUEUE_INCOMING_MESSAGE.HEADER;
    }

    @Override
    public Field<String> field3() {
        return QueueIncomingMessage.QUEUE_INCOMING_MESSAGE.PAYLOAD;
    }

    @Override
    public Field<Integer> field4() {
        return QueueIncomingMessage.QUEUE_INCOMING_MESSAGE.PROCESSING_STATUS;
    }

    @Override
    public Field<String> field5() {
        return QueueIncomingMessage.QUEUE_INCOMING_MESSAGE.PROCESSING_STATUS_MESSAGE;
    }

    @Override
    public Field<String> field6() {
        return QueueIncomingMessage.QUEUE_INCOMING_MESSAGE.REFERENCE;
    }

    @Override
    public Field<String> field7() {
        return QueueIncomingMessage.QUEUE_INCOMING_MESSAGE.STATUS;
    }

    @Override
    public Field<String> field8() {
        return QueueIncomingMessage.QUEUE_INCOMING_MESSAGE.TOPIC;
    }

    @Override
    public Field<Boolean> field9() {
        return QueueIncomingMessage.QUEUE_INCOMING_MESSAGE.TREAT_IMMEDIATELY;
    }

    @Override
    public Field<String> field10() {
        return QueueIncomingMessage.QUEUE_INCOMING_MESSAGE.TIME_ADDED;
    }

    @Override
    public Field<String> field11() {
        return QueueIncomingMessage.QUEUE_INCOMING_MESSAGE.TIME_UPDATED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getHeader();
    }

    @Override
    public String component3() {
        return getPayload();
    }

    @Override
    public Integer component4() {
        return getProcessingStatus();
    }

    @Override
    public String component5() {
        return getProcessingStatusMessage();
    }

    @Override
    public String component6() {
        return getReference();
    }

    @Override
    public String component7() {
        return getStatus();
    }

    @Override
    public String component8() {
        return getTopic();
    }

    @Override
    public Boolean component9() {
        return getTreatImmediately();
    }

    @Override
    public String component10() {
        return getTimeAdded();
    }

    @Override
    public String component11() {
        return getTimeUpdated();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getHeader();
    }

    @Override
    public String value3() {
        return getPayload();
    }

    @Override
    public Integer value4() {
        return getProcessingStatus();
    }

    @Override
    public String value5() {
        return getProcessingStatusMessage();
    }

    @Override
    public String value6() {
        return getReference();
    }

    @Override
    public String value7() {
        return getStatus();
    }

    @Override
    public String value8() {
        return getTopic();
    }

    @Override
    public Boolean value9() {
        return getTreatImmediately();
    }

    @Override
    public String value10() {
        return getTimeAdded();
    }

    @Override
    public String value11() {
        return getTimeUpdated();
    }

    @Override
    public QueueIncomingMessageRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public QueueIncomingMessageRecord value2(String value) {
        setHeader(value);
        return this;
    }

    @Override
    public QueueIncomingMessageRecord value3(String value) {
        setPayload(value);
        return this;
    }

    @Override
    public QueueIncomingMessageRecord value4(Integer value) {
        setProcessingStatus(value);
        return this;
    }

    @Override
    public QueueIncomingMessageRecord value5(String value) {
        setProcessingStatusMessage(value);
        return this;
    }

    @Override
    public QueueIncomingMessageRecord value6(String value) {
        setReference(value);
        return this;
    }

    @Override
    public QueueIncomingMessageRecord value7(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public QueueIncomingMessageRecord value8(String value) {
        setTopic(value);
        return this;
    }

    @Override
    public QueueIncomingMessageRecord value9(Boolean value) {
        setTreatImmediately(value);
        return this;
    }

    @Override
    public QueueIncomingMessageRecord value10(String value) {
        setTimeAdded(value);
        return this;
    }

    @Override
    public QueueIncomingMessageRecord value11(String value) {
        setTimeUpdated(value);
        return this;
    }

    @Override
    public QueueIncomingMessageRecord values(Long value1, String value2, String value3, Integer value4, String value5, String value6, String value7, String value8, Boolean value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QueueIncomingMessageRecord
     */
    public QueueIncomingMessageRecord() {
        super(QueueIncomingMessage.QUEUE_INCOMING_MESSAGE);
    }

    /**
     * Create a detached, initialised QueueIncomingMessageRecord
     */
    public QueueIncomingMessageRecord(Long id, String header, String payload, Integer processingStatus, String processingStatusMessage, String reference, String status, String topic, Boolean treatImmediately, String timeAdded, String timeUpdated) {
        super(QueueIncomingMessage.QUEUE_INCOMING_MESSAGE);

        setId(id);
        setHeader(header);
        setPayload(payload);
        setProcessingStatus(processingStatus);
        setProcessingStatusMessage(processingStatusMessage);
        setReference(reference);
        setStatus(status);
        setTopic(topic);
        setTreatImmediately(treatImmediately);
        setTimeAdded(timeAdded);
        setTimeUpdated(timeUpdated);
    }
}
