/*
 * This file is generated by jOOQ.
 */
package com.julianduru.oauthservice.jooq.tables.records;


import com.julianduru.oauthservice.jooq.tables.ResourceServer;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourceServerRecord extends UpdatableRecordImpl<ResourceServerRecord> implements Record7<Long, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oauth_service.resource_server.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oauth_service.resource_server.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oauth_service.resource_server.auth_role_id</code>.
     */
    public void setAuthRoleId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oauth_service.resource_server.auth_role_id</code>.
     */
    public String getAuthRoleId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oauth_service.resource_server.auth_username</code>.
     */
    public void setAuthUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oauth_service.resource_server.auth_username</code>.
     */
    public String getAuthUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oauth_service.resource_server.time_added</code>.
     */
    public void setTimeAdded(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oauth_service.resource_server.time_added</code>.
     */
    public String getTimeAdded() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oauth_service.resource_server.time_updated</code>.
     */
    public void setTimeUpdated(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oauth_service.resource_server.time_updated</code>.
     */
    public String getTimeUpdated() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oauth_service.resource_server.resource_server_id</code>.
     */
    public void setResourceServerId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oauth_service.resource_server.resource_server_id</code>.
     */
    public String getResourceServerId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oauth_service.resource_server.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oauth_service.resource_server.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ResourceServer.RESOURCE_SERVER.ID;
    }

    @Override
    public Field<String> field2() {
        return ResourceServer.RESOURCE_SERVER.AUTH_ROLE_ID;
    }

    @Override
    public Field<String> field3() {
        return ResourceServer.RESOURCE_SERVER.AUTH_USERNAME;
    }

    @Override
    public Field<String> field4() {
        return ResourceServer.RESOURCE_SERVER.TIME_ADDED;
    }

    @Override
    public Field<String> field5() {
        return ResourceServer.RESOURCE_SERVER.TIME_UPDATED;
    }

    @Override
    public Field<String> field6() {
        return ResourceServer.RESOURCE_SERVER.RESOURCE_SERVER_ID;
    }

    @Override
    public Field<String> field7() {
        return ResourceServer.RESOURCE_SERVER.STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAuthRoleId();
    }

    @Override
    public String component3() {
        return getAuthUsername();
    }

    @Override
    public String component4() {
        return getTimeAdded();
    }

    @Override
    public String component5() {
        return getTimeUpdated();
    }

    @Override
    public String component6() {
        return getResourceServerId();
    }

    @Override
    public String component7() {
        return getStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAuthRoleId();
    }

    @Override
    public String value3() {
        return getAuthUsername();
    }

    @Override
    public String value4() {
        return getTimeAdded();
    }

    @Override
    public String value5() {
        return getTimeUpdated();
    }

    @Override
    public String value6() {
        return getResourceServerId();
    }

    @Override
    public String value7() {
        return getStatus();
    }

    @Override
    public ResourceServerRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ResourceServerRecord value2(String value) {
        setAuthRoleId(value);
        return this;
    }

    @Override
    public ResourceServerRecord value3(String value) {
        setAuthUsername(value);
        return this;
    }

    @Override
    public ResourceServerRecord value4(String value) {
        setTimeAdded(value);
        return this;
    }

    @Override
    public ResourceServerRecord value5(String value) {
        setTimeUpdated(value);
        return this;
    }

    @Override
    public ResourceServerRecord value6(String value) {
        setResourceServerId(value);
        return this;
    }

    @Override
    public ResourceServerRecord value7(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ResourceServerRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResourceServerRecord
     */
    public ResourceServerRecord() {
        super(ResourceServer.RESOURCE_SERVER);
    }

    /**
     * Create a detached, initialised ResourceServerRecord
     */
    public ResourceServerRecord(Long id, String authRoleId, String authUsername, String timeAdded, String timeUpdated, String resourceServerId, String status) {
        super(ResourceServer.RESOURCE_SERVER);

        setId(id);
        setAuthRoleId(authRoleId);
        setAuthUsername(authUsername);
        setTimeAdded(timeAdded);
        setTimeUpdated(timeUpdated);
        setResourceServerId(resourceServerId);
        setStatus(status);
    }
}
