/*
 * This file is generated by jOOQ.
 */
package com.julianduru.oauthservice.jooq.tables.records;


import com.julianduru.oauthservice.jooq.tables.ResourceServerUserAuthoritiesOnSignUp;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourceServerUserAuthoritiesOnSignUpRecord extends TableRecordImpl<ResourceServerUserAuthoritiesOnSignUpRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oauth_service.resource_server_user_authorities_on_sign_up.resource_server_id</code>.
     */
    public void setResourceServerId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oauth_service.resource_server_user_authorities_on_sign_up.resource_server_id</code>.
     */
    public Long getResourceServerId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oauth_service.resource_server_user_authorities_on_sign_up.user_authorities_on_sign_up</code>.
     */
    public void setUserAuthoritiesOnSignUp(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oauth_service.resource_server_user_authorities_on_sign_up.user_authorities_on_sign_up</code>.
     */
    public String getUserAuthoritiesOnSignUp() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ResourceServerUserAuthoritiesOnSignUp.RESOURCE_SERVER_USER_AUTHORITIES_ON_SIGN_UP.RESOURCE_SERVER_ID;
    }

    @Override
    public Field<String> field2() {
        return ResourceServerUserAuthoritiesOnSignUp.RESOURCE_SERVER_USER_AUTHORITIES_ON_SIGN_UP.USER_AUTHORITIES_ON_SIGN_UP;
    }

    @Override
    public Long component1() {
        return getResourceServerId();
    }

    @Override
    public String component2() {
        return getUserAuthoritiesOnSignUp();
    }

    @Override
    public Long value1() {
        return getResourceServerId();
    }

    @Override
    public String value2() {
        return getUserAuthoritiesOnSignUp();
    }

    @Override
    public ResourceServerUserAuthoritiesOnSignUpRecord value1(Long value) {
        setResourceServerId(value);
        return this;
    }

    @Override
    public ResourceServerUserAuthoritiesOnSignUpRecord value2(String value) {
        setUserAuthoritiesOnSignUp(value);
        return this;
    }

    @Override
    public ResourceServerUserAuthoritiesOnSignUpRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResourceServerUserAuthoritiesOnSignUpRecord
     */
    public ResourceServerUserAuthoritiesOnSignUpRecord() {
        super(ResourceServerUserAuthoritiesOnSignUp.RESOURCE_SERVER_USER_AUTHORITIES_ON_SIGN_UP);
    }

    /**
     * Create a detached, initialised ResourceServerUserAuthoritiesOnSignUpRecord
     */
    public ResourceServerUserAuthoritiesOnSignUpRecord(Long resourceServerId, String userAuthoritiesOnSignUp) {
        super(ResourceServerUserAuthoritiesOnSignUp.RESOURCE_SERVER_USER_AUTHORITIES_ON_SIGN_UP);

        setResourceServerId(resourceServerId);
        setUserAuthoritiesOnSignUp(userAuthoritiesOnSignUp);
    }
}
