/*
 * This file is generated by jOOQ.
 */
package com.julianduru.oauthservice.jooq.tables.records;


import com.julianduru.oauthservice.jooq.tables.UserData;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDataRecord extends UpdatableRecordImpl<UserDataRecord> implements Record14<Long, String, String, String, String, String, String, String, String, String, Boolean, Boolean, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oauth_service.user_data.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oauth_service.user_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oauth_service.user_data.auth_role_id</code>.
     */
    public void setAuthRoleId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oauth_service.user_data.auth_role_id</code>.
     */
    public String getAuthRoleId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oauth_service.user_data.auth_username</code>.
     */
    public void setAuthUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oauth_service.user_data.auth_username</code>.
     */
    public String getAuthUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oauth_service.user_data.time_added</code>.
     */
    public void setTimeAdded(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oauth_service.user_data.time_added</code>.
     */
    public String getTimeAdded() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oauth_service.user_data.time_updated</code>.
     */
    public void setTimeUpdated(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oauth_service.user_data.time_updated</code>.
     */
    public String getTimeUpdated() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oauth_service.user_data.additional_info</code>.
     */
    public void setAdditionalInfo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oauth_service.user_data.additional_info</code>.
     */
    public String getAdditionalInfo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>oauth_service.user_data.email</code>.
     */
    public void setEmail(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>oauth_service.user_data.email</code>.
     */
    public String getEmail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>oauth_service.user_data.password</code>.
     */
    public void setPassword(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>oauth_service.user_data.password</code>.
     */
    public String getPassword() {
        return (String) get(7);
    }

    /**
     * Setter for <code>oauth_service.user_data.username</code>.
     */
    public void setUsername(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>oauth_service.user_data.username</code>.
     */
    public String getUsername() {
        return (String) get(8);
    }

    /**
     * Setter for <code>oauth_service.user_data.authorities</code>.
     */
    public void setAuthorities(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>oauth_service.user_data.authorities</code>.
     */
    public String getAuthorities() {
        return (String) get(9);
    }

    /**
     * Setter for <code>oauth_service.user_data.credentials_expired</code>.
     */
    public void setCredentialsExpired(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>oauth_service.user_data.credentials_expired</code>.
     */
    public Boolean getCredentialsExpired() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>oauth_service.user_data.locked</code>.
     */
    public void setLocked(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>oauth_service.user_data.locked</code>.
     */
    public Boolean getLocked() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>oauth_service.user_data.first_name</code>.
     */
    public void setFirstName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>oauth_service.user_data.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>oauth_service.user_data.last_name</code>.
     */
    public void setLastName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>oauth_service.user_data.last_name</code>.
     */
    public String getLastName() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, String, String, String, String, String, String, String, String, Boolean, Boolean, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, String, String, String, String, String, String, String, String, String, Boolean, Boolean, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserData.USER_DATA.ID;
    }

    @Override
    public Field<String> field2() {
        return UserData.USER_DATA.AUTH_ROLE_ID;
    }

    @Override
    public Field<String> field3() {
        return UserData.USER_DATA.AUTH_USERNAME;
    }

    @Override
    public Field<String> field4() {
        return UserData.USER_DATA.TIME_ADDED;
    }

    @Override
    public Field<String> field5() {
        return UserData.USER_DATA.TIME_UPDATED;
    }

    @Override
    public Field<String> field6() {
        return UserData.USER_DATA.ADDITIONAL_INFO;
    }

    @Override
    public Field<String> field7() {
        return UserData.USER_DATA.EMAIL;
    }

    @Override
    public Field<String> field8() {
        return UserData.USER_DATA.PASSWORD;
    }

    @Override
    public Field<String> field9() {
        return UserData.USER_DATA.USERNAME;
    }

    @Override
    public Field<String> field10() {
        return UserData.USER_DATA.AUTHORITIES;
    }

    @Override
    public Field<Boolean> field11() {
        return UserData.USER_DATA.CREDENTIALS_EXPIRED;
    }

    @Override
    public Field<Boolean> field12() {
        return UserData.USER_DATA.LOCKED;
    }

    @Override
    public Field<String> field13() {
        return UserData.USER_DATA.FIRST_NAME;
    }

    @Override
    public Field<String> field14() {
        return UserData.USER_DATA.LAST_NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAuthRoleId();
    }

    @Override
    public String component3() {
        return getAuthUsername();
    }

    @Override
    public String component4() {
        return getTimeAdded();
    }

    @Override
    public String component5() {
        return getTimeUpdated();
    }

    @Override
    public String component6() {
        return getAdditionalInfo();
    }

    @Override
    public String component7() {
        return getEmail();
    }

    @Override
    public String component8() {
        return getPassword();
    }

    @Override
    public String component9() {
        return getUsername();
    }

    @Override
    public String component10() {
        return getAuthorities();
    }

    @Override
    public Boolean component11() {
        return getCredentialsExpired();
    }

    @Override
    public Boolean component12() {
        return getLocked();
    }

    @Override
    public String component13() {
        return getFirstName();
    }

    @Override
    public String component14() {
        return getLastName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAuthRoleId();
    }

    @Override
    public String value3() {
        return getAuthUsername();
    }

    @Override
    public String value4() {
        return getTimeAdded();
    }

    @Override
    public String value5() {
        return getTimeUpdated();
    }

    @Override
    public String value6() {
        return getAdditionalInfo();
    }

    @Override
    public String value7() {
        return getEmail();
    }

    @Override
    public String value8() {
        return getPassword();
    }

    @Override
    public String value9() {
        return getUsername();
    }

    @Override
    public String value10() {
        return getAuthorities();
    }

    @Override
    public Boolean value11() {
        return getCredentialsExpired();
    }

    @Override
    public Boolean value12() {
        return getLocked();
    }

    @Override
    public String value13() {
        return getFirstName();
    }

    @Override
    public String value14() {
        return getLastName();
    }

    @Override
    public UserDataRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserDataRecord value2(String value) {
        setAuthRoleId(value);
        return this;
    }

    @Override
    public UserDataRecord value3(String value) {
        setAuthUsername(value);
        return this;
    }

    @Override
    public UserDataRecord value4(String value) {
        setTimeAdded(value);
        return this;
    }

    @Override
    public UserDataRecord value5(String value) {
        setTimeUpdated(value);
        return this;
    }

    @Override
    public UserDataRecord value6(String value) {
        setAdditionalInfo(value);
        return this;
    }

    @Override
    public UserDataRecord value7(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserDataRecord value8(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserDataRecord value9(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UserDataRecord value10(String value) {
        setAuthorities(value);
        return this;
    }

    @Override
    public UserDataRecord value11(Boolean value) {
        setCredentialsExpired(value);
        return this;
    }

    @Override
    public UserDataRecord value12(Boolean value) {
        setLocked(value);
        return this;
    }

    @Override
    public UserDataRecord value13(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public UserDataRecord value14(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public UserDataRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Boolean value11, Boolean value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserDataRecord
     */
    public UserDataRecord() {
        super(UserData.USER_DATA);
    }

    /**
     * Create a detached, initialised UserDataRecord
     */
    public UserDataRecord(Long id, String authRoleId, String authUsername, String timeAdded, String timeUpdated, String additionalInfo, String email, String password, String username, String authorities, Boolean credentialsExpired, Boolean locked, String firstName, String lastName) {
        super(UserData.USER_DATA);

        setId(id);
        setAuthRoleId(authRoleId);
        setAuthUsername(authUsername);
        setTimeAdded(timeAdded);
        setTimeUpdated(timeUpdated);
        setAdditionalInfo(additionalInfo);
        setEmail(email);
        setPassword(password);
        setUsername(username);
        setAuthorities(authorities);
        setCredentialsExpired(credentialsExpired);
        setLocked(locked);
        setFirstName(firstName);
        setLastName(lastName);
    }
}
