/*
 * This file is generated by jOOQ.
 */
package com.julianduru.oauthservice.jooq;


import com.julianduru.oauthservice.jooq.tables.Databasechangelog;
import com.julianduru.oauthservice.jooq.tables.Databasechangeloglock;
import com.julianduru.oauthservice.jooq.tables.Oauth2Authorization;
import com.julianduru.oauthservice.jooq.tables.Oauth2AuthorizationConsent;
import com.julianduru.oauthservice.jooq.tables.Oauth2RegisteredClient;
import com.julianduru.oauthservice.jooq.tables.ResourceServer;
import com.julianduru.oauthservice.jooq.tables.ResourceServerAllowedScopes;
import com.julianduru.oauthservice.jooq.tables.ResourceServerUserAuthoritiesOnSignUp;
import com.julianduru.oauthservice.jooq.tables.UserData;


/**
 * Convenience access to all tables in oauth_service.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>oauth_service.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>oauth_service.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>oauth_service.oauth2_authorization</code>.
     */
    public static final Oauth2Authorization OAUTH2_AUTHORIZATION = Oauth2Authorization.OAUTH2_AUTHORIZATION;

    /**
     * The table <code>oauth_service.oauth2_authorization_consent</code>.
     */
    public static final Oauth2AuthorizationConsent OAUTH2_AUTHORIZATION_CONSENT = Oauth2AuthorizationConsent.OAUTH2_AUTHORIZATION_CONSENT;

    /**
     * The table <code>oauth_service.oauth2_registered_client</code>.
     */
    public static final Oauth2RegisteredClient OAUTH2_REGISTERED_CLIENT = Oauth2RegisteredClient.OAUTH2_REGISTERED_CLIENT;

    /**
     * The table <code>oauth_service.resource_server</code>.
     */
    public static final ResourceServer RESOURCE_SERVER = ResourceServer.RESOURCE_SERVER;

    /**
     * The table <code>oauth_service.resource_server_allowed_scopes</code>.
     */
    public static final ResourceServerAllowedScopes RESOURCE_SERVER_ALLOWED_SCOPES = ResourceServerAllowedScopes.RESOURCE_SERVER_ALLOWED_SCOPES;

    /**
     * The table <code>oauth_service.resource_server_user_authorities_on_sign_up</code>.
     */
    public static final ResourceServerUserAuthoritiesOnSignUp RESOURCE_SERVER_USER_AUTHORITIES_ON_SIGN_UP = ResourceServerUserAuthoritiesOnSignUp.RESOURCE_SERVER_USER_AUTHORITIES_ON_SIGN_UP;

    /**
     * The table <code>oauth_service.user_data</code>.
     */
    public static final UserData USER_DATA = UserData.USER_DATA;
}
